name: Simple CI/CD Workflow

on:
  push:
    branches:
      - ecommerce  # ç›‘å¬ ecommerce åˆ†æ”¯ä¸Šçš„æ¨é€äº‹ä»¶

jobs:
  build:
    runs-on: ubuntu-latest  # ä½¿ç”¨ Ubuntu æœåŠ¡å™¨

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # æ£€å‡ºä»£ç 

      - name: Print a message
        run: echo "ğŸš€ CI/CD workflow is running successfully on the 'ecommerce' branch!"
